stages:
  - test
  - build

debian-unittest:
  image: biolds/sosse:deb-test
  stage: test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - se/migrations/*.py
      - htmlcov/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  script:
    - /etc/init.d/postgresql start
    - mkdir -p /var/lib/sosse/screenshots/ /var/lib/sosse/downloads/0 && chown -R www-data:www-data /var/lib/sosse/
    - /usr/bin/python3 /root/httpbin/httpbin/manage.py runserver 0.0.0.0:8000 &
    - sudo -u www-data python3-coverage run -a --source se,sosse ./sosse-admin default_conf | sed -e "s/^#db_pass=.*/db_pass=sosse/" -e "s/^#debug=.*/debug=true/" -e "s/^#browser_options=\(.*\)/browser_options=\1 --no-sandbox/" -e "s/#dl_check_time=.*/dl_check_time=0.5/" > /etc/sosse/sosse.conf
    - sudo -u www-data python3-coverage run -a --source se,sosse ./sosse-admin test -v3 --failfast
    - sudo -u www-data python3-coverage run -a --source se,sosse ./sosse-admin load_se tests/opensearch.xml
    - mkdir /usr/share/sosse/
    - cp se.json /usr/share/sosse/
    - sudo -u www-data python3-coverage run -a --source se,sosse ./sosse-admin update_se
    - sudo -u www-data ./sosse-admin shell -c 'from django.contrib.auth.models import User; User.objects.all().delete()'
    - sudo -u www-data python3-coverage run -a --source se,sosse ./sosse-admin default_admin
    - sudo -u www-data python3-coverage run -a --source se,sosse ./sosse-admin generate_secret
    - python3 ./sosse-admin makemigrations
    - python3-coverage report
    - python3-coverage html
    - python3-coverage xml

migrations:
  image: biolds/sosse:deb-test
  stage: test
  script:
    - /etc/init.d/postgresql start
    - sudo -u www-data python3 ./sosse-admin default_conf | sed -e "s/^#db_pass=.*/db_pass=sosse/" -e "s/^#debug=.*/debug=true/" > /etc/sosse/sosse.conf
    - MIGRATION_COUNT="$(ls se/migrations/*.py|grep '/[0-9]'|wc -l)"
    - python3 ./sosse-admin makemigrations
    - MIGRATION_COUNT2="$(ls se/migrations/*.py|grep '/[0-9]'|wc -l)"
    - test "$MIGRATION_COUNT" -eq "$MIGRATION_COUNT2"

static_checks:
  image: biolds/sosse:deb-test
  stage: test
  script:
    - flake8 --ignore=E501,W503,W504 --exclude=migrations
    - 'for f in $(find -name \*.py|grep -v /__init__\.py$) ; do grep -q "^# Copyright" "$f" || echo "File $f does not have a copyright header" ; done'
    - 'for f in $(find -name \*.py|grep -v /__init__\.py$) ; do grep -q "^# Copyright" "$f" || exit 1 ; done'

debian-pkg:
  image: registry.gitlab.com/biolds1/sosse/debian-pkg:latest
  stage: build
  artifacts:
    paths:
      - deb/*.deb
  script:
    - cd "$CI_PROJECT_DIR"
    - rm -rf htmlcov
    - echo "SOSSE_VERSION_TAG = '$CI_COMMIT_TAG'" >> sosse/settings.py
    - echo "SOSSE_VERSION_COMMIT = '${CI_COMMIT_SHORT_SHA}'" >> sosse/settings.py
    - mkdir /deb
    - make _deb
    - mv /deb .
